// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLIBc_g8mIm6bfwvu1jzNZA0l1S5fPI0k',
    appId: '1:471877407566:android:b1ef849698f935e1d0841f',
    messagingSenderId: '471877407566',
    projectId: 'jebly-prod',
    databaseURL: 'https://jebly-prod-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jebly-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfn0gAOerc6qqXEMuY0JUfWJ1grhQaQqY',
    appId: '1:471877407566:ios:6db29cc77a30ba93d0841f',
    messagingSenderId: '471877407566',
    projectId: 'jebly-prod',
    databaseURL: 'https://jebly-prod-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jebly-prod.firebasestorage.app',
    iosBundleId: 'com.jebly.customer',
  );
}
